//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onmoticaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class onEmail
    {
        public int id { get; set; }
        public Nullable<int> usrId { get; set; }
        public string usrEmail { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
