//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onmoticaData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class onHubEntities : DbContext
    {
        public onHubEntities()
            : base("name=onHubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<measurement> measurements { get; set; }
        public virtual DbSet<onEmail> onEmails { get; set; }
        public virtual DbSet<onUser> onUsers { get; set; }
        public virtual DbSet<personalData> personalDatas { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<thing> things { get; set; }
        public virtual DbSet<thingTyp> thingTyps { get; set; }
        public virtual DbSet<userTyp> userTyps { get; set; }
    }
}
