//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onmoticaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class personalData
    {
        public int id { get; set; }
        public Nullable<int> usrId { get; set; }
        public string profilePhoto { get; set; }
        public string cellphone { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string facebookURL { get; set; }
        public string twitterURL { get; set; }
        public string linkedinURL { get; set; }
    }
}
