//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onmoticaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> thingId { get; set; }
        public Nullable<int> usrId { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string field1Max { get; set; }
        public string field2Max { get; set; }
        public string field3Max { get; set; }
        public string field4Max { get; set; }
        public string field5Max { get; set; }
        public string field6Max { get; set; }
        public string field7Max { get; set; }
        public string field8Max { get; set; }
        public string field9Max { get; set; }
        public string field10Max { get; set; }
        public string field11Max { get; set; }
        public string field12Max { get; set; }
        public string field13Max { get; set; }
        public string field14Max { get; set; }
        public string field15Max { get; set; }
        public string field1Min { get; set; }
        public string field2Min { get; set; }
        public string field3Min { get; set; }
        public string field4Min { get; set; }
        public string field5Min { get; set; }
        public string field6Min { get; set; }
        public string field7Min { get; set; }
        public string field8Min { get; set; }
        public string field9Min { get; set; }
        public string field10Min { get; set; }
        public string field11Min { get; set; }
        public string field12Min { get; set; }
        public string field13Min { get; set; }
        public string field14Min { get; set; }
        public string field15Min { get; set; }
        public string field1AVG { get; set; }
        public string field2AVG { get; set; }
        public string field3AVG { get; set; }
        public string field4AVG { get; set; }
        public string field5AVG { get; set; }
        public string field6AVG { get; set; }
        public string field7AVG { get; set; }
        public string field8AVG { get; set; }
        public string field9AVG { get; set; }
        public string field10AVG { get; set; }
        public string field11AVG { get; set; }
        public string field12AVG { get; set; }
        public string field13AVG { get; set; }
        public string field14AVG { get; set; }
        public string field15AVG { get; set; }
    }
}
