//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onmoticaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTyp
    {
        public int id { get; set; }
        public Nullable<int> buyPlan { get; set; }
        public Nullable<int> description { get; set; }
        public Nullable<int> price { get; set; }
    }
}
